
run:
	slideshow talk.rkt

run-wide:
	slideshow --widescreen talk.rkt

print:
	slideshow --pdf talk.rkt

run-basics:
	slideshow slideshow-basics.rkt

print-basics:
	slideshow --pdf slideshow-basics.rkt

clean:
	rm -rf *~
	rm -rf slideshow-basics.pdf talk.pdf
	rm -rf compiled/
